### ISSUE TITLE
Libro digitale liquido

### ISSUE THREAD

**Issue by Idontgivefuck** [Leone25/samona-downloader#1]
Buonasera,
avrei bisogno di scaricare un libro digitale liquido che non viene rilevato dallo script, come posso fare?

**Comment by Leone25** [comment]
I libri liquidi sono un inferno da gestire dato che non c'è un formato comune a cui esportarli, quindi attualmente non rientrano nello scopo dello script.


Ovviamente chiunque é benvenuto a contribuire...
